### ISSUE TITLE
Other work to consider/incorporate

### ISSUE THREAD

**Issue by mr-c** [research-software/citation#4]
http://bit.ly/shouldacite

**Comment by sdruskat** [comment]
Thanks @mr-c! Included shouldacite link in a footnote at https://research-software.org/citation/researchers/. I chose a footnote because I didn't want to digress from the main focus too much at this point.

Please let me know if you'd like to be added to the contributors list on the page itself (this is now asked in the issue template as well), and if so, how (name + ORCID perhaps?). Once I got round to cleaning the sources a touch, people can do this themselves as well.

**Comment by sdruskat** [comment]
Also adding it to the projects list on the index page.

**Comment by mr-c** [comment]
Thank you @sdruskat 
I'm Michael R. Crusoe https://orcid.org/0000-0002-2961-9670
